import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { UserPlus, Users, Search, Filter } from 'lucide-react';

const UserManagement = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    role: '',
    department: ''
  });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [usersList, setUsersList] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeTab, setActiveTab] = useState('coordinator');
  const baseURL = '';
  const [editingUserId, setEditingUserId] = useState(null);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const res = await axios.get(`${baseURL}/api/admin/users`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
      });
      setUsersList(res.data);
    } catch (err) {
      console.error('Failed to fetch users', err);
    }
  };

  const handleEditClick = (user) => {
    setEditingUserId(user.id);
    setFormData({
      name: user.name,
      email: user.email,
      password: '',
      role: user.role,
      department: user.department || ''
    });
    setMessage('');
    setError('');
  };

  const handleDeleteClick = async (userId) => {
    if (!window.confirm("Are you sure you want to delete this user?")) return;
    try {
      await axios.delete(`${baseURL}/api/admin/users/${userId}`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
      });
      setMessage('User deleted successfully.');
      fetchUsers();
    } catch (err) {
      setError(err.response?.data?.detail || 'Error deleting user');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage('');
    setError('');
    try {
      if (editingUserId) {
        await axios.put(`${baseURL}/api/admin/users/${editingUserId}`, formData, {
          headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
        });
        setMessage(`Successfully updated ${formData.name}!`);
        setEditingUserId(null);
      } else {
        await axios.post(`${baseURL}/api/admin/users`, formData, {
          headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
        });
        setMessage(`Successfully created credentials for ${formData.email}!`);
      }
      setFormData({ name: '', email: '', password: '', role: '', department: '' });
      fetchUsers();
    } catch (err) {
      setError(err.response?.data?.detail || 'Error processing request');
    }
  };

  // Filter users based on search
  const searchedUsers = usersList.filter(u => 
    u.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
    u.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
    (u.department && u.department.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  // Derive sections
  const coordinators = searchedUsers.filter(u => u.role === 'coordinator');
  const clubCoordinators = searchedUsers.filter(u => u.role === 'club_coordinator');
  const finance = searchedUsers.filter(u => u.role === 'finance');
  const faculty = searchedUsers.filter(u => u.role === 'faculty');
  const students = searchedUsers.filter(u => u.role === 'student');
  const admins = searchedUsers.filter(u => u.role === 'admin');
  
  // Custom section for club members (anyone who has at least one club)
  const clubMembers = searchedUsers.filter(u => u.clubs && u.clubs.length > 0);

  const getActiveList = () => {
    switch (activeTab) {
      case 'coordinator': return coordinators;
      case 'club_coordinator': return clubCoordinators;
      case 'finance': return finance;
      case 'faculty': return faculty;
      case 'student': return students;
      case 'club_members': return clubMembers;
      case 'admin': return admins;
      default: return searchedUsers;
    }
  };

  const activeUsers = getActiveList();

  const renderTable = (users) => (
    <div style={{ overflowX: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
        <thead>
          <tr style={{ borderBottom: '2px solid var(--glass-border)', color: 'var(--text-muted)' }}>
            <th style={{ padding: '1rem 0.5rem' }}>Name</th>
            <th style={{ padding: '1rem 0.5rem' }}>Email</th>
            <th style={{ padding: '1rem 0.5rem' }}>Role</th>
            <th style={{ padding: '1rem 0.5rem' }}>Department</th>
            <th style={{ padding: '1rem 0.5rem' }}>Generated By</th>
            {activeTab === 'club_members' && (
              <th style={{ padding: '1rem 0.5rem' }}>Club Memberships</th>
            )}
            <th style={{ padding: '1rem 0.5rem', textAlign: 'right' }}>Actions</th>
          </tr>
        </thead>
        <tbody>
          {users.map(u => (
            <tr key={u.id} style={{ borderBottom: '1px solid var(--glass-border)' }}>
              <td style={{ padding: '1rem 0.5rem', fontWeight: 500 }}>{u.name}</td>
              <td style={{ padding: '1rem 0.5rem', color: 'var(--text-muted)' }}>{u.email}</td>
              <td style={{ padding: '1rem 0.5rem' }}>
                <span style={{ 
                  padding: '0.25rem 0.5rem', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 600, textTransform: 'capitalize',
                  background: u.role === 'admin' ? '#fee2e2' : u.role === 'coordinator' ? '#dbeafe' : '#f1f5f9',
                  color: u.role === 'admin' ? '#991b1b' : u.role === 'coordinator' ? '#1e40af' : '#475569'
                }}>
                  {u.role}
                </span>
              </td>
              <td style={{ padding: '1rem 0.5rem' }}>{u.department || '-'}</td>
              <td style={{ padding: '1rem 0.5rem', color: 'var(--text-muted)' }}>
                {u.created_by_role ? (
                  <span style={{ fontSize: '0.85rem', textTransform: 'capitalize' }}>{u.created_by_role}</span>
                ) : (
                  <span style={{ fontSize: '0.85rem', opacity: 0.5 }}>System</span>
                )}
              </td>
              {activeTab === 'club_members' && (
                <td style={{ padding: '1rem 0.5rem' }}>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                    {u.clubs?.map((c, i) => (
                      <span key={i} style={{ fontSize: '0.85rem', color: '#0369a1', fontWeight: 500 }}>
                        {c.club_name} ({c.role})
                      </span>
                    ))}
                  </div>
                </td>
              )}
              <td style={{ padding: '1rem 0.5rem', textAlign: 'right', display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
                <button 
                  onClick={() => handleEditClick(u)} 
                  style={{ padding: '0.4rem 0.8rem', background: '#e0f2fe', color: '#0369a1', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 600 }}
                >
                  Edit
                </button>
                <button 
                  onClick={() => handleDeleteClick(u.id)} 
                  style={{ padding: '0.4rem 0.8rem', background: '#fee2e2', color: '#991b1b', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 600 }}
                >
                  Delete
                </button>
              </td>
            </tr>
          ))}
          {users.length === 0 && (
            <tr>
              <td colSpan={activeTab === 'club_members' ? 7 : 6} style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                No users found in this section.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );

  const renderStudentTableGrouped = (users) => {
    const depts = [...new Set(users.map(u => u.department).filter(Boolean))].sort();
    const noDeptUsers = users.filter(u => !u.department);
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
        {depts.map(dept => (
          <div key={dept}>
             <h4 style={{ margin: '0 0 1rem 0', color: 'var(--primary)', borderBottom: '2px solid var(--primary)', paddingBottom: '0.5rem', fontSize: '1.2rem' }}>{dept} Students</h4>
             {renderTable(users.filter(u => u.department === dept))}
          </div>
        ))}
        {noDeptUsers.length > 0 && (
          <div>
             <h4 style={{ margin: '0 0 1rem 0', color: 'var(--primary)', borderBottom: '2px solid var(--primary)', paddingBottom: '0.5rem', fontSize: '1.2rem' }}>Students (No Department)</h4>
             {renderTable(noDeptUsers)}
          </div>
        )}
      </div>
    );
  };

  const studentDepts = [...new Set(students.map(s => s.department).filter(Boolean))].sort();

  const tabs = [
    { id: 'coordinator', label: 'Dept Coordinators', count: coordinators.length },
    { id: 'club_coordinator', label: 'Club Coordinators', count: clubCoordinators.length },
    { id: 'finance', label: 'Finance', count: finance.length },
    { id: 'faculty', label: 'Faculty', count: faculty.length },
    { id: 'student', label: 'All Dept Students', count: students.length },
    { id: 'club_members', label: 'Club Members', count: clubMembers.length },
    { id: 'admin', label: 'Admins', count: admins.length },
    { id: 'all', label: 'All Users', count: searchedUsers.length }
  ];

  return (
    <div style={{ padding: '2rem', display: 'grid', gridTemplateColumns: '1fr 2.5fr', gap: '2rem' }}>
      
      {/* LEFT: Generation / Edit Form */}
      <div className="glass-card" style={{ padding: '2rem', height: 'fit-content', position: 'sticky', top: '100px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
          <UserPlus size={28} color="var(--primary)" />
          <h2 style={{ margin: 0, color: 'var(--primary)' }}>
            {editingUserId ? "Edit User" : "Generate User"}
          </h2>
        </div>
        
        <p style={{ color: 'var(--text-muted)', marginBottom: '2rem' }}>
          {editingUserId 
            ? "Modify the selected user's details and roles." 
            : "Generate new user credentials for staff."}
        </p>

        {message && <div style={{ padding: '1rem', background: '#dcfce7', color: '#166534', borderRadius: '6px', marginBottom: '1rem' }}>{message}</div>}
        {error && <div style={{ padding: '1rem', background: '#fee2e2', color: '#991b1b', borderRadius: '6px', marginBottom: '1rem' }}>{error}</div>}

        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.2rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>Full Name</label>
            <input type="text" className="input-glass" required value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} />
          </div>
          
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>University Email</label>
            <input type="email" className="input-glass" required value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} />
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>
              {editingUserId ? "New Password (Optional)" : "Temporary Password"}
            </label>
            <input type="text" className="input-glass" required={!editingUserId} value={formData.password} onChange={e => setFormData({...formData, password: e.target.value})} placeholder={editingUserId ? "Leave blank to keep same" : ""} />
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>System Role</label>
            <select className="input-glass" required value={formData.role} onChange={e => setFormData({...formData, role: e.target.value})}>
              <option value="" disabled>Select Role</option>
              <option value="student">Student</option>
              <option value="faculty">Faculty</option>
              <option value="coordinator">Department Coordinator</option>
              <option value="club_coordinator">University Club Coordinator</option>
              <option value="finance">Finance</option>
              <option value="admin">Admin</option>
            </select>
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>Department (Required for Coord/Student)</label>
            <select className="input-glass" value={formData.department} onChange={e => setFormData({...formData, department: e.target.value})}>
              <option value="">None / System Wide</option>
              <option value="CSE">CSE</option>
              <option value="ECE">ECE</option>
              <option value="ME">ME</option>
              <option value="EE">EE</option>
              <option value="CE">CE</option>
              <option value="BBA">BBA</option>
              <option value="BCA">BCA</option>
            </select>
          </div>

          <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
            <button type="submit" className="btn-primary" style={{ flex: 1, padding: '0.8rem' }}>
              {editingUserId ? "Update User" : "Generate"}
            </button>
            {editingUserId && (
              <button 
                type="button" 
                className="btn-secondary" 
                style={{ flex: 1, padding: '0.8rem' }}
                onClick={() => {
                  setEditingUserId(null);
                  setFormData({ name: '', email: '', password: '', role: '', department: '' });
                  setMessage('');
                  setError('');
                }}
              >
                Cancel
              </button>
            )}
          </div>
        </form>
      </div>

      {/* RIGHT: List of Users grouped by section */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        
        {/* Search Bar */}
        <div className="glass-card" style={{ padding: '1rem 2rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <Search color="var(--text-muted)" />
          <input 
            type="text" 
            placeholder="Search users by name, email, or department..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{ border: 'none', background: 'transparent', outline: 'none', flex: 1, fontSize: '1rem' }}
          />
        </div>

        <div className="glass-card" style={{ padding: '2rem', minHeight: '600px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2rem' }}>
            <Users size={28} color="var(--primary)" />
            <h2 style={{ margin: 0, color: 'var(--primary)' }}>User Directory</h2>
          </div>
          
          {/* Tabs for Sections */}
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '2rem', flexWrap: 'wrap', borderBottom: '2px solid var(--glass-border)', paddingBottom: '1rem' }}>
            {tabs.map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                style={{
                  padding: '0.5rem 1rem',
                  borderRadius: '20px',
                  border: 'none',
                  cursor: 'pointer',
                  fontWeight: 600,
                  fontSize: '0.9rem',
                  background: activeTab === tab.id ? 'var(--primary)' : 'transparent',
                  color: activeTab === tab.id ? 'white' : 'var(--text-muted)',
                  transition: 'all 0.2s'
                }}
              >
                {tab.label} <span style={{ opacity: 0.8, fontSize: '0.8rem' }}>({tab.count})</span>
              </button>
            ))}
          </div>

          {/* Table */}
          {activeTab === 'student' ? renderStudentTableGrouped(activeUsers) : renderTable(activeUsers)}
        </div>
      </div>
    </div>
  );
};

export default UserManagement;
